### ISSUE TITLE
V9 - Resizing of various symbols could be improved / fixed

### ISSUE THREAD

**Issue by lucastobrazil** [IBM/carbon-design-kit#46]
## Overview
It looks like certain constraints are missing / components have not been tested with resizing with different content etc. This makes it a bit difficult to use the sketch library without making my own modifications. 

## Detailed description

Although it's super helpful to have all of the sketch symbols, many of them do not resize correctly when using overrides, adding different content or resizing to fit a layout.

I assume this is just an oversight because there's obviously been a lot of work put in to creating them and documenting :)

> What version of the Carbon Design System Kit are you using?
9.0.0

## Additional information
What happens currently:
![screen shot 2018-08-29 at 16 42 50](https://user-images.githubusercontent.com/8508891/44795382-d3bd7900-abaa-11e8-9a8a-01a020b93fd3.png)

What should happen:
![screen shot 2018-08-29 at 16 44 27](https://user-images.githubusercontent.com/8508891/44795389-d8822d00-abaa-11e8-82e9-b3cd879142ff.png)

Also a similar issue with the Accordion:
![screen shot 2018-08-29 at 17 00 50](https://user-images.githubusercontent.com/8508891/44796350-1aac6e00-abad-11e8-889a-c41feed671ad.png)

**Comment by laurenmrice** [comment]
Fixed ✅
