### ISSUE TITLE
V9 - Text of Tag components is not editable

### ISSUE THREAD

**Issue by fakob** [IBM/carbon-design-kit#47]
## Detailed description
The text of the tag components is not editable and the component itself can not be resized.
In the Carbon Design Kit sketch file all Tag elements and also their text layers are locked. And the width and height of the background is fixed.

> What version of the Carbon Design System Kit are you using?
9.0.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Tags

> What did you expect to happen? What happened instead? What would you like to see changed?
I expect to be able to edit the text and resize the tag to fit the text.

## Add labels
`library`

**Comment by laurenmrice** [comment]
Fixed ✅
