### ISSUE TITLE
Small secondary button with icon is missing

### ISSUE THREAD

**Issue by fakob** [IBM/carbon-design-kit#48]
## Detailed description

Small secondary button with icon is missing. It shows up on [](http://carbondesignsystem.com/components/button/code), but I could not find it in the sketch file.

> What version of the Carbon Design System Kit are you using?
9.0.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
button

## Add labels
`library`

**Comment by aagonzales** [comment]
Adding to v9.0.1
