### ISSUE TITLE
Thumbnail missing in Add Library screen

### ISSUE THREAD

**Issue by coolpillows** [IBM/carbon-design-kit#49]
Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file. 
_just library_

> What version of the Carbon Design System Kit are you using - 
_9_

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name. 
_just the thumbnail_

> What did you expect to happen? What happened instead? What would you like to see changed?
_i was having a bunch of crashes with Sketch and doubt this is related but that's why i noticed this._ 

<img width="522" alt="library_thumbnail_missing" src="https://user-images.githubusercontent.com/15839032/45502892-38540880-b753-11e8-8c30-89ba4fa4be22.png">

**Comment by aagonzales** [comment]
The image comes from the first page in the file called "Cover". It is working for me not sure why it wouldn't show for you.

**Comment by aagonzales** [comment]
Actually, I know what it is. The image comes from the last page of the kit that has been opened. So if you opened the kit as a normal Sketch file and didn't close/save it on the cover page then it won't load the correct preview.
