### ISSUE TITLE
v10 - Create a new sketch library for experimental components

### ISSUE THREAD

**Issue by shinytoyrobots** [IBM/carbon-design-kit#50]
As a designer, I can download an experimental sketch library and use it to play around with some of the new component designs

DESIGN
- [ ] create experimental component section in Sketch library
- [ ] confirm component designs are approved and copy to library

Remember to include:
- [ ] Cell behaviors
- [ ] Centering options (vertical, horizontal)
- [ ] Optical centering or actual centering
- [ ] Skeleton state

Scope: Derived from **what exists in code**. I.e. only components that are available for use.

**Comment by shinytoyrobots** [comment]
Can update the description / tasks above based on discussion of scope in sprint planning meeting.

**Comment by aagonzales** [comment]
Components done:
- [ ] 01 Accordion
- [ ] 02 Breadcrumb
- [ ] 03 Button
- [ ] 04 Checkbox
- [ ] 05 Code Snippet
- [ ] 06 Content Switcher
- [ ] 07 Data table THANKYOU
- [ ] 08 Date Picker
- [ ] 09 Dropdown
- [ ] 10 File Uploader
- [ ] 11 Form
- [ ] 12 Link
- [ ] 13 List
- [ ] 14 Loading
- [ ] Inline loading
- [ ] 15 Modal
- [ ] 16 Notification
- [ ] 17 Number Input
- [ ] 18 Overflow Menu
- [ ] 19 Pagination 
- [ ] 20 Progress Indicator
- [ ] 21 Radiobox
- [ ] 22 Search
- [ ] 23 Select
- [ ] 24 Slider
- [ ] 25 Structured List
- [ ] 26 Tabs
- [ ] 27 Tags
- [ ] 28 Text Input
- [ ] 29 Tile
- [ ] 30 Toggle
- [ ] 31 Tooltip

**Comment by aagonzales** [comment]
**Remaining tasks:**
- [ ] clean up file
- [ ] remove components layer in symbol structure? 
- [ ] combine files and double check assets
- [ ] clean up symbols page
- [ ] update getting started page
- [ ] update what's new page

Other:
- [ ] Need to create other theme sketch assets: https://github.com/IBM/carbon-design-kit/issues/70

**Comment by aagonzales** [comment]
Done!
