### ISSUE TITLE
Add license file to project

### ISSUE THREAD

**Issue by mikelax** [IBM/carbon-design-kit#54]
## Detailed description

A license file should be added to the project and configured for the project so it's clear for users that want to take and utilize these resources.

**Comment by laurenmrice** [comment]
@chrisconnors-ibm  ^

**Comment by chrisconnors-ibm** [comment]
this has been @kuehndaniel's area of expertise

**Comment by kuehndaniel** [comment]
@mikelax We have a LICENSE file for our components as well as our elements packages. Is there something else you're looking for?

https://github.com/IBM/carbon-components
https://github.com/IBM/carbon-elements

**Comment by mikelax** [comment]
Thanks @kuehndaniel 
I was looking for a top level license file for this repo, similar to how you have the code of conduct  and contributing files set up. 

This makes it easy to see quickly when viewing the repo the license attached.

**Comment by joshblack** [comment]
Is there a particular license in this area that you're expecting to see @mikelax? Maybe something like a creative commons? Could help us figure out what to license it under 😄 Our other projects are under Apache-2.0, but I think we're all unsure how to license a sketch file in this case.

**Comment by chrisconnors-ibm** [comment]
does adding the license from here: https://github.com/IBM/carbon-components/blob/master/LICENSE to https://github.com/IBM/carbon-design-kit

close this issue?

**Comment by mikelax** [comment]
@chrisconnors-ibm  yeah I think that would solve the issue. The apache 2 license matches some other open source design systems such as grommet.

**Comment by chrisconnors-ibm** [comment]
@joshblack or @aagonzales the PR above adds the same license file from carbon-components to carbon-design-kit
