### ISSUE TITLE
All icon symbol artboards should be equal size

### ISSUE THREAD

**Issue by rauhala** [IBM/carbon-design-kit#55]
## Detailed description
Some icon overrides within components in Sketch design kit doesn't work properly. Take a Add-on/Card for example. There are two icons (restart and launch) in the component, which can be overrided if needed. However, for restart-icon overrides, only those few icons which artboard is 13x16px are offered and for launch-icon overrides, all the icons, which artboard is 16x16px are offered. See attached images.

> What version of the Carbon Design System Kit are you using?

9.0.0

> What did you expect to happen? What happened instead? What would you like to see changed?

In my opinion all icons should be available to be used as an override whenever there is an icon symbol included in the component. Sketch works so, that is looks up the artboards equal size and lets user select among those, so that's why all the icon symbol artboards should be same size.

## Additional information
<img width="1054" alt="screenshot 2018-10-09 at 21 30 44" src="https://user-images.githubusercontent.com/16488270/46708343-2c514e80-cc0c-11e8-9616-31f131c019dc.png">
<img width="1083" alt="screenshot 2018-10-09 at 21 31 01" src="https://user-images.githubusercontent.com/16488270/46708344-2c514e80-cc0c-11e8-926c-5346ec64a8cb.png">

**Comment by joshblack** [comment]
cc @IBM/carbon-designers

**Comment by aagonzales** [comment]
We will be fixing this in the next major release (v10)
