### ISSUE TITLE
V9 - Getting started page in 9.0.1 show version 9.0.0

### ISSUE THREAD

**Issue by rauhala** [IBM/carbon-design-kit#58]
## Detailed description
I feel that the `Getting started` and `What's new` pages should reflect what has been changed, even though changes would be small bug fixes. Otherwise it is hard to keep track between versions.

Now v. 9.0.1 displays exactly the same information than v. 9.0.0.

> What version of the Carbon Design System Kit are you using?
9.0.1

**Comment by aagonzales** [comment]
Good catch, that should have been updated. We'll be sure too update that next time. Not sure its worth pushing a new version for that just yet. I'll leave this issue open to remind us.

**Comment by laurenmrice** [comment]
Fixed ✅
