### ISSUE TITLE
V9 - Capitalization issues with Button and Content Switcher

### ISSUE THREAD

**Issue by JordanWSmith15** [IBM/carbon-design-kit#62]
The standard seems to be sentence-case, but occasionally, title case is used. See attachment. 
![button](https://user-images.githubusercontent.com/21066152/48423150-0dc00500-e72e-11e8-84d9-d0d08b758730.jpg)
<img width="476" alt="content swticher" src="https://user-images.githubusercontent.com/21066152/48423151-0dc00500-e72e-11e8-8ef1-cb63d00cc665.png">

**Comment by laurenmrice** [comment]
Fixed ✅
