### ISSUE TITLE
Lightning Weather Pictogram - Broken (Bolt section)

### ISSUE THREAD

**Issue by kweaverTWC** [IBM/carbon-design-kit#65]
When I was trying to use the weather pictograms from the IBM Design Language Sketch Kit Library, I noticed that the lightning bolt in the icon was missing its top half! I noticed that to fix it all that was needed was to reorder the fill shapes in the symbol.

IBM Design Language.Sketch -> Page: Pictograms -> Symbol: Pictograms/weather/ (should be more descriptive?) 

![image](https://user-images.githubusercontent.com/25778007/48564832-2dd5fc80-e8c5-11e8-9b3f-0f2a5a008911.png)

**Comment by aagonzales** [comment]
This is an issue in the IBM Design Language Kit - I will try and track down the better place to but this issue.

**Comment by eraymond25** [comment]
pushed a fix! Love the visuals on this issue @kweaverTWC it was great!

I also went in and named a bunch of those weather icons, it's a WIP so let me know if you have any thoughts!

**Comment by kweaverTWC** [comment]
@eraymond25 Great, thanks! The IBM set is too basic to incorporate into our apps right now, but maybe in the future we could expand the set. Right now we have about 32 icons for our weather icons. Some extend the severity of weather conditions like rain/drizzle, snow-showers/flurries etc. Just something to think about, thanks again!
