### ISSUE TITLE
V9 - Hex number off by 1 number in the sketch palette

### ISSUE THREAD

**Issue by steviesharp123** [IBM/carbon-design-kit#67]
Hex number off by 1 number in the sketch palette

Text 1 off of the website
<img width="179" alt="screen shot 2018-12-03 at 2 11 16 pm" src="https://user-images.githubusercontent.com/11092490/49399728-b6e39500-f707-11e8-97f7-e4f91844194c.png">

Text 1 in the sketch palette
![screen shot 2018-12-03 at 2 11 32 pm](https://user-images.githubusercontent.com/11092490/49399729-b6e39500-f707-11e8-8bd1-fc35e2a95c30.png)

**Comment by laurenmrice** [comment]
Fixed ✅
