### ISSUE TITLE
Cannot import into sketch 51.3

### ISSUE THREAD

**Issue by mtsweir** [IBM/carbon-design-kit#68]
After downloading the latest version (9.0.1), I cannot import this file into Sketch.

## Steps to reproduce the issue

1. Open Preferences and go to Libraries tab
2. Add to [Library...](url)
3. Select sketch file [(9.0.1)](url)

## Additional information

* See attached screenshot
<img width="581" alt="screen shot 2018-12-24 at 12 13 40 pm" src="https://user-images.githubusercontent.com/4976660/50388465-220b0f00-077c-11e9-9ff3-de8cb37c7dd4.png">

**Comment by stefanogreg-ibm** [comment]
It has been Specified that you need the Latest Sketch Version which is 52.
You can use the 9.0.0 version which works with Sketch 51.x

**Comment by mtsweir** [comment]
@stefanogreg-ibm cheers for the follow up :-)
