### ISSUE TITLE
V9 kit bugs

### ISSUE THREAD

**Issue by aagonzales** [IBM/carbon-design-kit#71]
Need to clean up V9 kit bugs before we stop support on it. Need to update because teams will still be using it over the next several month. Look at other issues in the repo for tasks. 

- [x] Rename Cover Layer in Sketch Template
- [x] V9 - Text of Tag components is not editable
- [x] V9 - Hex number off by 1 number in the sketch palette
- [x] V9 - Capitalization issues with Button and Content Switcher
- [x] V9 - Getting started page in 9.0.1 show version 9.0.0
- [x] Create .crl file
- [x] Sketch Palette corruption
- [x] Update color palette file
- [x] Green and Blue support colors do not pass color contrast test issue
- [x] V9 - Resizing of various symbols could be improved / fixed 
- [x] check buttons are responding correctly
- [x] fixed accordion
- [x] fixed notifications
- [x] fixed dropdowns
- [x] fixed date picker
- [x] fixed number input
- [x] fixed tooltip
- [x] fixed errors on templates

**Comment by aagonzales** [comment]
https://github.com/ibm/carbon-design-kit/issues

**Comment by laurenmrice** [comment]
done ✅
