### ISSUE TITLE
V10 Kit - add skeleton states

### ISSUE THREAD

**Issue by aagonzales** [IBM/carbon-design-kit#72]
Need to add skeleton states to the V10 Kit.

**Comment by laurenmrice** [comment]
- [ ] Accordion
- [ ] Breadcrumb
- [ ] Button
- [ ] Checkbox
- [ ] Code snippet
- [ ] Content switcher
- [ ] Data table
- [ ] Date picker
- [ ] File uploader
- [ ] Form
- [ ] Link
- [ ] List
- [ ] Loading
- [ ] Modal
- [ ] Notification
- [ ] Number input
- [ ] Overflow menu
- [ ] Pagination
- [ ] Progress indicator
- [ ] Radio button
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Structured list
- [ ] Tabs
- [ ] Tag
- [ ] Text input
- [ ] Tile
- [ ] Toggle
- [ ] Tooltip

**Comment by laurenmrice** [comment]
Sketch file: https://ibm.ent.box.com/file/431649632657
