### ISSUE TITLE
Rename Cover Layer in Sketch Template

### ISSUE THREAD

**Issue by bscheid** [IBM/carbon-design-kit#74]
## Detailed description

According to Sketch's library creation instructions, the cover layer needs to be renamed to Library Preview so a logo will appear next to the library. 

> What version of the Carbon Design System Kit are you using? 0.9

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.  Cover layer

> What did you expect to happen? What happened instead? What would you like to see changed? Naming of layers

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency? No

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? No impact on an offering, just a nice to have.

## Steps to reproduce the issue

1. Open SketchStep one
2. Open the Sketch preferences (Sketch->Preferemces) and select the library tab
3. Click Add library
4. Select Carbon Design Kit.sketch from your local file system
5. Upon return to the preference dialog you will notice that the Carbon library is added but does not have a logo. 

## Additional information
See https://www.sketchapp.com/docs/libraries/adding-libraries paragraph 5/6 which includes details on how to add an icon to a library. 

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by laurenmrice** [comment]
Fixed ✅
